@startuml
' Layout Direction
left to right direction

' Define Objects
object "Document : readDocumentVerify" as doc {
  characters = List<Character>
  propertiesFactory = CharacterPropertiesFactory
}

object "CharacterPropertiesFactory : propertiesFactory" as cpf <<factory>> {
  flyweights = HashMap<String, CharacterProperties>
}

' Characters Properties Instances
object "CharacterProperties : ArialBlack14" as CP1 {
  font = "Arial"
  color = "Black"
  size = 14
}
object "CharacterProperties : ArialBlack16" as CP2 {
  font = "Arial"
  color = "Black"
  size = 16
}
object "CharacterProperties : VerdanaBlue18" as CP3 {
  font = "Verdana"
  color = "Blue"
  size = 18
}
object "CharacterProperties : VerdanaRed12" as CP4 {
  font = "Verdana"
  color = "Red"
  size = 12
}

object "CharacterProperties : CalibriBlue99" as CP5 {
  font = "Calibri"
  color = "Blue"
  size = 99
}

' Define Characters
object "Character : H" as Ch1 {
  character = 'H'
}
object "Character : e" as Ch2 {
  character = 'e'
}
object "Character : l1" as Ch3 {
  character = 'l'
}
object "Character : l2" as Ch4 {
  character = 'l'
}
object "Character : o1" as Ch5 {
  character = 'o'
}
object "Character : W" as Ch6 {
  character = 'W'
}
object "Character : o2" as Ch7 {
  character = 'o'
}
object "Character : r" as Ch8 {
  character = 'r'
}
object "Character : l3" as Ch9 {
  character = 'l'
}
object "Character : d" as Ch10 {
  character = 'd'
}
object "Character : C" as Ch11 {
  character = 'C'
}
object "Character : S" as Ch12 {
  character = 'S'
}
object "Character : 5" as Ch13 {
  character = '5'
}
object "Character : 8" as Ch14 {
  character = '8'
}
object "Character : 0_1" as Ch15 {
  character = '0'
}
object "Character : 0_2" as Ch16 {
  character = '0'
}

' Add space for readability
cpf -[hidden]-> CP1
cpf -[hidden]-> CP2
cpf -[hidden]-> CP3
cpf -[hidden]-> CP4

' Define Relationships
doc *-- cpf : "owns a"
doc *-- Ch1 : "owns a"
doc *-- Ch2 : "owns a"
doc *-- Ch3 : "owns a"
doc *-- Ch4 : "owns a"
doc *-- Ch5 : "owns a"
doc *-- Ch6 : "owns a"
doc *-- Ch7 : "owns a"
doc *-- Ch8 : "owns a"
doc *-- Ch9 : "owns a"
doc *-- Ch10 : "owns a"
doc *-- Ch11 : "owns a"
doc *-- Ch12 : "owns a"
doc *-- Ch13 : "owns a"
doc *-- Ch14 : "owns a"
doc *-- Ch15 : "owns a"
doc *-- Ch16 : "owns a"

cpf o-- CP1 : "manages"
cpf o-- CP2 : "manages"
cpf o-- CP3 : "manages"
cpf o-- CP4 : "manages"
cpf o-- CP5 : "manages"

Ch1 o-- CP5 : "has a"
Ch2 o-- CP1 : "has a"
Ch3 o-- CP1 : "has a"
Ch4 o-- CP1 : "has a"
Ch5 o-- CP1 : "has a"
Ch6 o-- CP5 : "has a"
Ch7 o-- CP1 : "has a"
Ch8 o-- CP1 : "has a"
Ch9 o-- CP1 : "has a"
Ch10 o-- CP1 : "has a"
Ch11 o-- CP3 : "has a"
Ch12 o-- CP3 : "has a"
Ch13 o-- CP4 : "has a"
Ch14 o-- CP4 : "has a"
Ch15 o-- CP4 : "has a"
Ch16 o-- CP4 : "has a"

@enduml
