@startuml
object testDocument {
    characters = "['H', 'e', 'l', 'l', 'o', 'W', 'o', 'r', 'l', 'd', 'C', 'S', '5', '8', '0', '0']"
}

object Character1 {
    character = 'H'
    property = CharacterProperties1
}

object Character2 {
    character = 'e'
    property = CharacterProperties2
}

object Character3 {
    character = 'l'
    property = CharacterProperties2
}

object Character4 {
    character = 'l'
    property = CharacterProperties2
}

object Character5 {
    character = 'o'
    property = CharacterProperties2
}

object Character6 {
    character = 'W'
    property = CharacterProperties1
}

object Character7 {
    character = 'o'
    property = CharacterProperties2
}

object Character8 {
    character = 'r'
    property = CharacterProperties2
}

object Character9 {
    character = 'l'
    property = CharacterProperties2
}

object Character10 {
    character = 'd'
    property = CharacterProperties2
}

object Character11 {
    character = 'C'
    property = CharacterProperties3
}

object Character12 {
    character = 'S'
    property = CharacterProperties3
}

object Character13 {
    character = '5'
    property = CharacterProperties4
}

object Character14 {
    character = '8'
    property = CharacterProperties4
}

object Character15 {
    character = '0'
    property = CharacterProperties4
}

object Character16 {
    character = '0'
    property = CharacterProperties4
}

object CharacterProperties1 {
    font = "Arial"
    size = 16
    color = "Black"
}

object CharacterProperties2 {
    font = "Arial"
    size = 14
    color = "Black"
}

object CharacterProperties3 {
    font = "Verdana"
    size = 18
    color = "Blue"
}

object CharacterProperties4 {
    font = "Verdana"
    size = 12
    color = "Red"
}

testDocument --> Character1 : contains
testDocument --> Character2 : contains
testDocument --> Character3 : contains
testDocument --> Character4 : contains
testDocument --> Character5 : contains
testDocument --> Character6 : contains
testDocument --> Character7 : contains
testDocument --> Character8 : contains
testDocument --> Character9 : contains
testDocument --> Character10 : contains
testDocument --> Character11 : contains
testDocument --> Character12 : contains
testDocument --> Character13 : contains
testDocument --> Character14 : contains
testDocument --> Character15 : contains
testDocument --> Character16 : contains

Character1 --> CharacterProperties1 : uses
Character6 --> CharacterProperties1 : uses
Character2 --> CharacterProperties2 : uses
Character3 --> CharacterProperties2 : uses
Character4 --> CharacterProperties2 : uses
Character5 --> CharacterProperties2 : uses
Character7 --> CharacterProperties2 : uses
Character8 --> CharacterProperties2 : uses
Character9 --> CharacterProperties2 : uses
Character10 --> CharacterProperties2 : uses
Character11 --> CharacterProperties3 : uses
Character12 --> CharacterProperties3 : uses
Character13 --> CharacterProperties4 : uses
Character14 --> CharacterProperties4 : uses
Character15 --> CharacterProperties4 : uses
Character16 --> CharacterProperties4 : uses
@enduml